services:
  keycloak_saml2:
    image: quay.io/keycloak/keycloak:26.0.4
    container_name: keycloak_saml2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8104:8080"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --log-level="INFO,org.apache.http.headers:DEBUG,org.apache.http.wire:DEBUG"
